# Generated by Django 2.1 on 2018-08-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('print_type', models.CharField(choices=[('M', 'Matte Finish'), ('L', 'Luster Finish'), ('S', 'Semi Gloss Finish'), ('P', 'Platinum Finish'), ('F', 'Fine Art Smooth Finish')], max_length=1)),
                ('print_size', models.CharField(choices=[('8W', '8 Wallets (2.5 x 3.5)'), ('4x6', '4x6'), ('5x7', '5x7'), ('8x10', '8x10'), ('8.5x11', '8.5x11'), ('11x14', '11x14'), ('13x19', '13x19')], max_length=10)),
                ('price', models.FloatField()),
            ],
        ),
    ]
