# Generated by Django 2.1 on 2018-08-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_carouselitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='button_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
