# Generated by Django 2.2.1 on 2019-06-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20180804_0328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
