# Generated by Django 2.1 on 2018-08-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_event_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gallery.Client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gallery.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='client',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='event',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='title',
        ),
        migrations.AddField(
            model_name='picture',
            name='gallery',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Gallery.Gallery'),
            preserve_default=False,
        ),
    ]
