# Generated by Django 2.2.1 on 2019-06-01 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_gallery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('print_type', models.CharField(max_length=200)),
                ('print_size', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gallery.Client'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gallery.Event'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='price_points',
            field=models.ManyToManyField(blank=True, to='Gallery.PricePoint'),
        ),
    ]
