# Generated by Django 2.2.1 on 2019-06-01 23:07

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0005_auto_20190601_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='doggos'),
        ),
    ]
